---
layout: page-menu
title: Debezium Roadmap
permalink: /roadmap/
---
:linkattrs:
:icons: font
:source-highlighter: highlight.js

This page describes the roadmap for upcoming work on Debezium.

Debezium is community-driven and as such the roadmap constantly evolves to reflect the users needs and contributions.
You can find a fine-grained list of planned issues and feature requests in our https://issues.redhat.com/browse/DBZ[issue tracker],
but this page is a good starting point to see where we are going.

This roadmap is subject to changes.
Please get https://groups.google.com/forum/#!forum/debezium[in touch] if you think anything important is missing on the roadmap.

[NOTE]
====
The Debezium community pursues a time-boxed release scheme: minor releases (1.2, 1.3, etc.) are done at the end of every quarter,
with preview releases (1.3.0.Alpha1, 1.3.0.Beta1, etc.) every three weeks.
As our engineering capacity is limited, we're focusing our efforts on a single release line at a time (e.g. 1.3),
i.e. patch releases for the current stable minor release (e.g. 1.2.1.Final) are done in case of critical bug fixes only.
====

== 3.1 - March 2025

* Oracle 12c support sunset (best-effort moving forward)
* Completed implementation and refactoring of MongoDB sink connector
* Message vectorization support (via SMT)
* Sink for InstructLab
* Sink for vector databases (TBD)
* Condition-based lifecycle control of Debezium Engine
* Revamped ExtractNewDocument state SMT to handle complex nested documents and arrays

== 3.2 - June 2025

* OpenLineage integration
* Debezium Server support for Debezium sink (MongoDB and JDBC) connectors
* Debezium Engine Quarkus integration
* Read-only incremental snapshot for MongoDB
* WebAssembly support in scripting transformations
* Support for two stage processing achitecture in Oracle connector
* Design/Implement user-friendly offset manipulation (i.e, start at a specific position in the transaction logs)

== 3.3 - September 2025

* Create PoC for implementing sagas (long-running business transactions spanning multiple (micro-)services) using CDC and the outbox pattern
* Explore and provide building blocks for implementing CQRS architectures based on change data streams
* Exactly-Once support for other connectors
* Additional monitoring - Quantimeter

== 3.4 - December 2025

* Read-only incremental snapshot for SQL Server and Oracle
* Add schema history compaction tool

== Future Releases

* Source connector for InfluxDB time series database
* Introduce an SPI to reduce memory footprint for multi-tenant databases with identical schemas

* Provide a Debezium-specific SPI for describing change event schemas
* API/SPI allowing to implement custom connectors on the foundations of Debezium
* Exploration of creating aggregated events, based on the streams/data from multiple tables, so to enable use cases which need to incorporate data from multiple tables into a single output structure (e.g. an Elasticsearch document containing order and orderline info)
* Support for Infinispan as a source
* Allow to propagate custom contextual data in change messages (e.g. the business user doing a certain change)
* Provide more detailed monitoring information about Debezium's internal state and health via JMX (e.g. to spot loss of DB connection while the connector still is running)
* Explore publication of change events via reactive data streams (on top of embedded connector)
* New implementation of the Debezium embedded engine independent of Kafka Connect APIs
* Debezium UI (Legacy) - New CLI tooling
** Incremental Snapshot interface
** Quick-start connector deployment
** Support varied Kafka Connect and Debezium versions
** Offset manipulation
* Debezium Operator
** Improved Observability and Metrics
** R&D to consider multitasking support with Debezium Server
** Integration with Distribution Builder

== Past Releases

Please see the link:/releases[releases overview] page to learn more about the contents of past Debezium releases.
